name: CI for Staging
on:
  pull_request:
    branches:
      - "release/v1.0.0"
jobs:
    linting_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Linting
              run: |
                npx htmlhint@1.1.4 "**/*.html"
                npx stylelint "**/*.css"
            - name: Build Artifact
              run: |
                npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
